url: "https://christianandjeff.com"
permalink: ":title/"
exclude:
  [
    "README.md",
    "CNAME",
    "Gemfile",
  ]
owner-name: "Jeffrey Louden"
owner-page: "https://jefflouden.com/"
owner-email: "jeff@jefflouden.com"
topic_list: ["articles"]
name: "Jeffrey Louden"

excerpt_separator: ""